/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2019-01-07

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include <stdint.h>
#include <stm32f4xx.h>
#include <stm32f4_discovery.h>
#include <serial.h>
#include "type_others.h"
#include <vt100.h>
//#include "heap.h"

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */

/* Commands to keep
 * vt100_clear_screen(); //clear the screen
 *
 * 	shoot_tab[0].x = ;
	shoot_tab[0].y = 32;
	shoot_tab[0].who = shoot_ally;

	shoot_tab[1].x = ;
	shoot_tab[1].y = 8;
	shoot_tab[1].who = shoot_ennemy;
 *
 */

pos ship = { .x=62, .y=34};
u_int8 ship_size = 5;

int main(void)
{
	/* Init com */


	serial_init(115200);

	u_int8 play = 1;	//start game
	state game = INIT;
	while (play)
	{
		switch (game)
		{
		case INIT :

			vt100_clear_screen();


			//	Init Ennemy fleet
			pos ennemy_tab[40];
			u_int8 end_game = 0;
			for (u_int8 i=0; i<=39; i++)
			{
				ennemy_tab[i].x = 0;
				ennemy_tab[i].y = 0;
				ennemy_tab[i].alive = 0;
				for (u_int8 j=0; j<=7; j++)
				{
					ennemy_tab[i].skin[j] = 0;
				}
			}
			direction fleet = right;
			extremum ennemy ;

			// Init shoot table
			shoot_pos shoot_tab[50];
			for (u_int8 i=0; i<=49; i++)
			{
				shoot_tab[i].x = 0;
				shoot_tab[i].y = 0;
				shoot_tab[i].who = shoot_ennemy;
			}

			// Serial reception init
			int8 serial_char = serial_get_last_char();

			u_int8 lives = 2;						//init number of lives

		case LOGO :
			// A beautiful logo
			vt100_move (50,25);
			serial_puts ("Press any touch to start");
			vt100_move (30,13);
			serial_puts ("    _____                          ____                     __               ");
			vt100_move (30,14);
			serial_puts ("   / ___/____  ____ _________     /  _/___ _   ______ _____/ /__  __________ ");
			vt100_move (30,15);
			serial_puts ("   \\__ \\/ __ \\/ __ `/ ___/ _ \\    / // __ \\ | / / __ `/ __  / _ \\/ ___/ ___/");
			vt100_move (30,16);
			serial_puts ("   __/ / /_/ / /_/ / /__/  __/  _/ // / / / |/ / /_/ / /_/ /  __/ /  (__  )  ");
			vt100_move (30,17);
			serial_puts (" /____/ .___/\\__,_/\\___/\\___/  /___/_/ /_/|___/\\__,_/\\__,_/\\___/_/  /____/");
			vt100_move (30,18);
			serial_puts ("     /_/                                                                     ");
			while (serial_char == 0xFF)							//waiting to start
			{
				serial_char = serial_get_last_char();
			}

			//easter egg
			if (serial_char == '=')
			{
				vt100_move (2,1);
				serial_puts ("cheat code : ");
				do
				{
					serial_char = serial_get_last_char();
				} while (serial_char == 0xFF);
				if (serial_char == 'n')
				{
					serial_putchar ('s');
					do
					{
						serial_char = serial_get_last_char();
					} while (serial_char == 0xFF);
					if (serial_char == 'w')
					{
						serial_putchar ('t');
						do
						{
							serial_char = serial_get_last_char();
						} while (serial_char == 0xFF);
						if (serial_char == 'c')
						{
							serial_putchar ('m');
							vt100_move (2,1);
							serial_puts ("Have fun, CHEATER~");
							lives = 50;
							goto gg;
						}
					}
				}
				vt100_move (1,1);
				serial_puts ("Not enough clever, yet~");
			}
gg :
			vt100_move (50,25);
			serial_puts ("                        ");
			vt100_move (50,25);
			serial_puts ("Ready...");

			u_int8 a = '3';										//around 3 sec delay
			for (a = '3'; a>'0' ; a--)
			{
				vt100_move(65, 20);
				serial_putchar (a);
				delay (9000000);
			}
				vt100_move(65, 20);
				serial_putchar (' ');		//clear 3/2/1

				vt100_move (50,25);
				serial_puts ("        ");	//clear 'Ready ...'
		case TEST :
			// for debug only



		case START :

			// Init game border
			border_init ();

			// Creating ship
			ship.x=62;								//initial position
			ship.y=34;
			vt100_move(ship.x,ship.y);
			serial_putship();						//create ship
			vt100_move (4,2);
			serial_puts ("Health bar : ");
			for (u_int8 i = 1; i <= lives; i++)
			{
				vt100_move (17+i,2);
				serial_putchar (219);
			}

			u_int8 cd_shoot = 0;					//init shoot cd

			//Creating ennemy fleet
			ennemy.min_x = 135;
			ennemy.max_x = 0;
			ennemy.max_y = 0;

			ennemy_type1 (ennemy_tab,  &ennemy);
			ennemy_type2 (ennemy_tab,  &ennemy);

			//Time before launch (with tIMER soon)
			delay(12000000);

		case GAME :
			while (lives >= 1)
			{
				// Ally moving
				move_ship (&ship, ship_size);

				// Ennemy fleet moving
				new_minmax (ennemy_tab, &ennemy);
				ennemy_moving (ennemy_tab, &fleet, &ennemy);
				ennemy_shooting (ennemy_tab, shoot_tab);

				// Ship Shooting
				ally_shooting (&cd_shoot, shoot_tab);

				// Shoots moving
				move_shoots (shoot_tab);

				// Something got hit ?
				hitbox (ennemy_tab, shoot_tab, &ship, &lives);

				// delay, between turns, randomly modifiable for now
				delay (400000);

				// game end ?
				if (ennemy_defeated (ennemy_tab) == 1)
				{
					end_game = 1;
					break;
				}
				if (ennemy.max_y >= 30)
				{
					end_game = 0;
					break;
				}
			}

		case END :
			vt100_clear_screen();
			if (end_game == 0)
			{
				vt100_move(65, 17);
				serial_puts ("You have been defeated ...");
			}
			else
			{
				vt100_move(65, 17);
				serial_puts ("You have defeated them... Well Played !");
			}

			vt100_move(50, 30);
			serial_puts ("Do you want to replay ? n for no");
			delay (5000000);
			serial_char = serial_get_last_char();
			while (serial_char == 0xFF)
			{
				serial_char = serial_get_last_char();
			}
			if (serial_char == 'n')
			{
				play = 0;
			}
			else
			{
				game = INIT;
			}
			break;
		}
	}
	vt100_clear_screen();
	while (1);
}
/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
	/* TODO, implement your code here */
	return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
	/* TODO, implement your code here */
	return -1;
}
