/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2019-01-07

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"
#include <serial.h>
#include <type_others.h>
#include <vt100.h>
#include <stdint.h>

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */

/* Commands to keep
 * vt100_clear_screen(); //clear the screen
 *
 * 	shoot_tab[0].x = ;
	shoot_tab[0].y = 32;
	shoot_tab[0].who = shoot_ally;

	shoot_tab[1].x = ;
	shoot_tab[1].y = 8;
	shoot_tab[1].who = shoot_ennemy;
 *
 */

pos ship = { .x=62, .y=34};
u_int8 ship_size = 5;
u_int8 PRNG = 43;		//Random value to start with

int main(void)
{
	/* Init com */
	serial_init(115200);

	u_int8 play = 1;
	state game = INIT;
	while (play)
	{
		switch (game)
		{
		case INIT :

			/* Init border */
			vt100_clear_screen();
			border_init ();

			/* Var Init */
			//	Init Ennemy fleet table
			pos ennemy_tab[30];
			for (u_int8 i=0; i<=29; i++)
			{
				ennemy_tab[i].x = 0;
				ennemy_tab[i].y = 0;
			}

			// Init shoot table
			shoot_pos shoot_tab[30];
			for (u_int8 i=0; i<=29; i++)
			{
				shoot_tab[i].x = 0;
				shoot_tab[i].y = 0;
				shoot_tab[i].who = shoot_ennemy;
			}

			// Serial reception init
			u_int8 serial_char = serial_get_last_char();

		case LOGO :
			// TODO make a beautiful logo
		{
			u_int8 a = '3';
			while (1)
			{
				delay (4500000);
				vt100_move(45, 15);
				serial_putchar (a);
				if (a == '0')
				{
					vt100_move(45, 15);
					serial_putchar (' ');
					break;
				}
				a--;
			}
		}
		case TEST :
			// if needs only

		case START :

			//Creating ship at initial position
			ship.x=62;
			ship.y=34;
			vt100_move(ship.x,ship.y);
			serial_putship();
			u_int8 alive = 1;
			u_int8 cd_shoot = 0;

			//Creating ennemy fleet
			u_int8 lenght_type1 = 0;
			ennemy_type1 (ennemy_tab, &lenght_type1);

			//Time before launch (with tIMER soon)
			delay(12000000);

		case WORKING :
			while (alive == 1)
			{
				// Ally moving
				move_ship (&ship, ship_size);

				// Ennemy fleet moving
				ennemy_shooting (ennemy_tab, shoot_tab);
				ennemy_moving (ennemy_tab);

				// Ship Shooting
				ally_shooting (&cd_shoot, shoot_tab);

				// Something got hit ?
				hitbox (ennemy_tab, shoot_tab, &ship, lenght_type1, &alive);

				// Shoots moving
				move_shoots (shoot_tab);

				// TODO delay, between turns, randomly modifiable for now
				delay (2000000);
			}
		case END :
			vt100_clear_screen();
			vt100_move(65, 17);
			serial_puts ("You have been defeated ...");
			vt100_move(50, 30);
			serial_puts ("Do you want to retry ? n for no");
			serial_char = serial_get_last_char();
			while (serial_char == -1);
			if (serial_char == 'n')
			{
				play = 0;
			}
			else;
			break;
		}
	}
	vt100_clear_screen();
	while (1);
}
/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
	/* TODO, implement your code here */
	return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
	/* TODO, implement your code here */
	return -1;
}
