/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2019-01-07

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"
#include <serial.h>
#include <type_others.h>
#include <vt100.h>
#include <stdint.h>

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */

/* Commands to keep
 * vt100_clear_screen(); //clear the screen
 *
 * 	shoot_tab[0].x = ;
	shoot_tab[0].y = 32;
	shoot_tab[0].who = shoot_ally;

	shoot_tab[1].x = ;
	shoot_tab[1].y = 8;
	shoot_tab[1].who = shoot_ennemy;
 *
 */

pos ship = { .x=62, .y=34};
u_int8 ship_size = 5;
u_int8 PRNG = 43;		//Random value to start with

int main(void)
{
	/** GAME INIT **/

	serial_init(115200);
	vt100_clear_screen();
	border_init ();
	/* Var Init */
	//	Init Ennemy fleet table
	pos ennemy_tab[30];
	for (u_int8 i=0; i<=29; i++)
	{
		ennemy_tab[i].x = 0;
		ennemy_tab[i].y = 0;
	}

	//Init shoot table
	shoot_pos shoot_tab[30];
	for (u_int8 i=0; i<=29; i++)
	{
		shoot_tab[i].x = 0;
		shoot_tab[i].y = 0;
		shoot_tab[i].who = shoot_ennemy;
	}
	u_int8 cd_shoot = 0;


	/* End of Var Init */

	//Creating ship at initial position
	vt100_move(ship.x,ship.y);
	serial_putship();


	//Creating ennemy fleet
	u_int8 lenght_type1 = 0;
	ennemy_type1 (ennemy_tab, &lenght_type1);

	// TESTS //



	/** GAME LAUNCH **/
	delay(12000000);
	while (1)
	{

		// Ennemy fleet moving
		ennemy_shooting (ennemy_tab, shoot_tab);
		//ennemy_moving ();

		// Ship Shooting
		ally_shooting (&cd_shoot, shoot_tab);

		// Something got hit ?
		hitbox (ennemy_tab, shoot_tab, &ship, lenght_type1);

		// Shoots moving
		move_shoots (shoot_tab);


		// TODO delay, between turns, randomly modifiable for now
		delay (4000000);
	}
}
/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
	/* TODO, implement your code here */
	return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
	/* TODO, implement your code here */
	return -1;
}
